site_name: sm4file
site_description: Python library for reading RHK .sm4 files.
site_url: https://matkrin.github.io/sm4file

theme:
  name: "material"

repo_name: matkrin/sm4file
repo_url: https://github.com/matkrin/sm4file

nav:
- Home: index.md
- Examples: examples.md
- API Reference: api-user.md
- For Developers:
  - Cursor: api-dev/cursor.md
  - Sm4File: api-dev/sm4_file_all.md
  - Object type: api-dev/sm4_object_types.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [.]
